#pragma checksum "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AD2C0F311A2FEEC1F37AECA43AA796E0F6AAB3A2"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class adminjobs1_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        
        #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
        protected global::System.Web.UI.WebControls.GridView gridJob;
        
        #line default
        #line hidden
        
        
        #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
        protected global::System.Web.UI.WebControls.SqlDataSource sqlJob;
        
        #line default
        #line hidden
        
        
        #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        #line default
        #line hidden
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        
        #line 4 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
                       

        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public adminjobs1_aspx() {
            string[] dependencies;
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/adminjobs1.aspx";
            if ((global::ASP.adminjobs1_aspx.@__initialized == false)) {
                global::ASP.adminjobs1_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[1];
                dependencies[0] = "~/adminjobs1.aspx";
                global::ASP.adminjobs1_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.adminjobs1_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 8 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl1;
            
            #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(30241, 485, true));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control4() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.NavigateUrl = "adminjob.aspx?id=0";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Add new Job"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLinkField @__BuildControl__control6() {
            global::System.Web.UI.WebControls.HyperLinkField @__ctrl;
            
            #line 27 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLinkField();
            
            #line default
            #line hidden
            
            #line 27 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataNavigateUrlFields = new string[] {
                    "Id"};
            
            #line default
            #line hidden
            
            #line 27 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataNavigateUrlFormatString = "adminjob.aspx?id={0}";
            
            #line default
            #line hidden
            
            #line 27 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataTextField = "JobCode";
            
            #line default
            #line hidden
            
            #line 27 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "JobCode";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control7() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 29 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataField = "ClientJobReqCode";
            
            #line default
            #line hidden
            
            #line 29 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "Client Code";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control8() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 30 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 30 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataField = "JobTitle";
            
            #line default
            #line hidden
            
            #line 30 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "Title";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control9() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 31 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataField = "Location";
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "Location";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control10() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 32 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataField = "JobDescription";
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "JobDescription";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control11() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 33 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataField = "PostedOn";
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataFormatString = "{0:d}";
            
            #line default
            #line hidden
            
            #line 33 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "Posted On";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control12() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 34 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 34 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataField = "Expiry";
            
            #line default
            #line hidden
            
            #line 34 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataFormatString = "{0:d}";
            
            #line default
            #line hidden
            
            #line 34 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "Expiry";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 35 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 35 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataField = "OFCCPRequired";
            
            #line default
            #line hidden
            
            #line 35 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.HeaderText = "OFCCP?";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.LinkButton @__BuildControl__control16() {
            global::System.Web.UI.WebControls.LinkButton @__ctrl;
            
            #line 38 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.LinkButton();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 38 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ID = "LinkButton1";
            
            #line default
            #line hidden
            
            #line 38 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.CausesValidation = false;
            
            #line default
            #line hidden
            
            #line 38 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.CommandName = "Delete";
            
            #line default
            #line hidden
            
            #line 38 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Text = "Delete";
            
            #line default
            #line hidden
            
            #line 38 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.OnClientClick = "return confirm(\'Are you certain you want to delete this Job?\');";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control15(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 36 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.LinkButton @__ctrl1;
            
            #line 36 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl1 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 36 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 36 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 36 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 36 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control15), null);
            
            #line default
            #line hidden
            
            #line 36 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ShowHeader = false;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control5(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.HyperLinkField @__ctrl1;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl1 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl2 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl3 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl4 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl5;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl5 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl6 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl7;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl7 = this.@__BuildControl__control12();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl8;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl8 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl9;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl9 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl9);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgridJob() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.gridJob = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ID = "gridJob";
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "Id"};
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DataSourceID = "sqlJob";
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.EmptyDataText = "No Jobs";
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ShowHeaderWhenEmpty = true;
            
            #line default
            #line hidden
            
            #line 24 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            this.@__BuildControl__control5(@__ctrl.Columns);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control18() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 48 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Name = "Id";
            
            #line default
            #line hidden
            
            #line 48 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Type = global::System.TypeCode.Int32;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control17(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.Parameter @__ctrl1;
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl1 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.SqlDataSource @__BuildControlsqlJob() {
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl;
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.SqlDataSource();
            
            #line default
            #line hidden
            this.sqlJob = @__ctrl;
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ID = "sqlJob";
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DeleteCommand = "DeleteJob";
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.DeleteCommandType = global::System.Web.UI.WebControls.SqlDataSourceCommandType.StoredProcedure;
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ProviderName = "System.Data.SqlClient";
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.SelectCommand = "GetAllJobs";
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.SelectCommandType = global::System.Web.UI.WebControls.SqlDataSourceCommandType.StoredProcedure;
            
            #line default
            #line hidden
            
            #line 44 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            this.@__BuildControl__control17(@__ctrl.DeleteParameters);
            
            #line default
            #line hidden
            @__ctrl.ConnectionString = global::System.Convert.ToString(System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting("ConnStr", typeof(System.Web.UI.WebControls.SqlDataSource), "ConnectionString"), global::System.Globalization.CultureInfo.CurrentCulture);
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl1;
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl1 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t<div>\r\n\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl2;
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl2 = this.@__BuildControlgridJob();
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl3;
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl3 = this.@__BuildControlsqlJob();
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 21 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t</div>\r\n\t"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(adminjobs1_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3" +
                        ".org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<body>\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs1.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n</body>\r\n</html>\r\n"));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.adminjobs1_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.adminjobs1_aspx.@__fileDependencies);
            this.ValidateRequestMode = System.Web.UI.ValidateRequestMode.Disabled;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -640160907;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
