#pragma checksum "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "B3D1ED206DE1190FC675CFC6D4B6F624E9F840E1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 299 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using System.Data;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using System.Data.SqlClient;
    
    #line default
    #line hidden
    
    #line 5 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using eWorld.UI;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class adminuser_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        
        #line 196 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
        
        #line default
        #line hidden
        
        
        #line 197 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::ASP.controls_adminmenu_ascx menu;
        
        #line default
        #line hidden
        
        
        #line 202 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textFirst;
        
        #line default
        #line hidden
        
        
        #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        
        #line default
        #line hidden
        
        
        #line 211 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textLast;
        
        #line default
        #line hidden
        
        
        #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorLast;
        
        #line default
        #line hidden
        
        
        #line 220 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textEmail;
        
        #line default
        #line hidden
        
        
        #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        
        #line default
        #line hidden
        
        
        #line 230 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textPassword;
        
        #line default
        #line hidden
        
        
        #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorPwd;
        
        #line default
        #line hidden
        
        
        #line 239 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::eWorld.UI.MaskedTextBox textPhone;
        
        #line default
        #line hidden
        
        
        #line 247 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textFBLog;
        
        #line default
        #line hidden
        
        
        #line 254 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textFBPass;
        
        #line default
        #line hidden
        
        
        #line 261 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textLinLog;
        
        #line default
        #line hidden
        
        
        #line 268 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textLinPass;
        
        #line default
        #line hidden
        
        
        #line 275 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textTwitLog;
        
        #line default
        #line hidden
        
        
        #line 282 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.TextBox textTwitPass;
        
        #line default
        #line hidden
        
        
        #line 287 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.ValidationSummary validJob;
        
        #line default
        #line hidden
        
        
        #line 288 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.WebControls.Button buttonSubmit;
        
        #line default
        #line hidden
        
        
        #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        #line default
        #line hidden
        
        
        #line 299 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
        protected global::ASP.Copyright copy;
        
        #line default
        #line hidden
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        
        #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
                       
	private int id;
	void Page_Init(object sender, EventArgs e)
	{
		if (!string.IsNullOrWhiteSpace(Request.QueryString["id"]))
		{
			Int32.TryParse(Request.QueryString["id"], out id);
		}
		if (!IsPostBack && id != 0)
		{
			using (SqlConnection _con = new SqlConnection(ConfigurationManager.AppSettings["ConnStr"]))
			{
				using (SqlCommand _command = new SqlCommand("GetUser", _con)
				{
					CommandType = CommandType.StoredProcedure
				})
				{
					_command.Parameters.AddWithValue("@Id", id);
					_con.Open();
					using (SqlDataReader _read = _command.ExecuteReader())
					{
						while (_read.Read())
						{
							textFirst.Text = _read.GetString(0);
							textLast.Text = _read.GetString(1);
							textEmail.Text = _read.GetString(2);
							textPhone.Text = _read.GetString(4);
							textPassword.Attributes["value"] = _read.GetString(3);
							textFBLog.Text = _read.IsDBNull(5) ? "" : _read.GetString(5);
							textFBPass.Attributes["value"] = _read.IsDBNull(6) ? "" : _read.GetString(6);
							textLinLog.Text = _read.IsDBNull(7) ? "" : _read.GetString(7);
							textLinPass.Attributes["value"] = _read.IsDBNull(8) ? "" : _read.GetString(8);
							textTwitLog.Text = _read.IsDBNull(9) ? "" : _read.GetString(9);
							textTwitPass.Attributes["value"] = _read.IsDBNull(10) ? "" : _read.GetString(10);
						}
					}
				}
			}
		}
	}

	void buttonSubmit_Click(object sender, EventArgs e)
	{
		using (SqlConnection _con = new SqlConnection(ConfigurationManager.AppSettings["ConnStr"]))
		{
			using (SqlCommand _command = new SqlCommand("SaveUser", _con)
			{
				CommandType = CommandType.StoredProcedure
			})
			{
				_command.Parameters.AddWithValue("@Id", id == 0 ? (object)DBNull.Value : id);
				_command.Parameters.AddWithValue("@First", textFirst.Text);
				_command.Parameters.AddWithValue("@Last", textLast.Text);
				_command.Parameters.AddWithValue("@Email", textEmail.Text);
				_command.Parameters.AddWithValue("@Phone", textPhone.Text);
				_command.Parameters.AddWithValue("@Password", textPassword.Text);
				_command.Parameters.AddWithValue("@LinLog", textLinLog.Text);
				_command.Parameters.AddWithValue("@LinPass", textLinPass.Text);
				_command.Parameters.AddWithValue("@FBLog", textFBLog.Text);
				_command.Parameters.AddWithValue("@FBPass", textFBPass.Text);
				_command.Parameters.AddWithValue("@TwitLog", textTwitLog.Text);
				_command.Parameters.AddWithValue("@TwitPass", textTwitPass.Text);
				_con.Open();
				_command.ExecuteNonQuery();
				Response.Redirect("adminusers.aspx", true);
			}
		}
	}

        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public adminuser_aspx() {
            string[] dependencies;
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/adminuser.aspx";
            if ((global::ASP.adminuser_aspx.@__initialized == false)) {
                global::ASP.adminuser_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[3];
                dependencies[0] = "~/adminuser.aspx";
                dependencies[1] = "~/controls/adminmenu.ascx";
                dependencies[2] = "~/controls/Copyright.ascx";
                global::ASP.adminuser_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.adminuser_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Content = "text/html; charset=iso-8859-1";
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("http-equiv", "Content-Type");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 92 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 92 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Content = "http://www.agreatis.com/images/logo_og.jpg";
            
            #line default
            #line hidden
            
            #line 92 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Content = "image/png";
            
            #line default
            #line hidden
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:type");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 94 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 94 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Content = "720";
            
            #line default
            #line hidden
            
            #line 94 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:width");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Content = "440";
            
            #line default
            #line hidden
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:height");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 97 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 97 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("AGREATIS, Inc."));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Href = "agreatis.css";
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Href = "Content/kendo/2012.3.1114/kendo.metro.min.css";
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control11() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 109 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 109 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Href = "Content/kendo/2012.3.1114/kendo.common.min.css";
            
            #line default
            #line hidden
            
            #line 109 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 109 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("prefix", "og: http://ogp.me/ns#");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t<!-- \r\n\t****************\r\n\tDescription: AGREATIS, Inc.\r\n\tCalled By : http://ww" +
                        "w.agreatis.com\r\n\tCreated: DonBosco Paily 07/30/2013\r\n\tLast Modified: DonBosco Pa" +
                        "ily 07/30/2013\r\n\t****************\r\n\t-->\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl2;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl3;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl4;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl4 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl5;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t<!-- #BeginEditable \"doctitle\" -->\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl6;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl6 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t<!-- #EndEditable -->\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl7;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl7 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(13633, 439, true));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl8;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl8 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl9;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl9 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(14072, 699, true));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlToolkitScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 196 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ToolkitScriptManager1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 196 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "ToolkitScriptManager1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::ASP.controls_adminmenu_ascx @__BuildControlmenu() {
            global::ASP.controls_adminmenu_ascx @__ctrl;
            
            #line 197 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::ASP.controls_adminmenu_ascx();
            
            #line default
            #line hidden
            this.menu = @__ctrl;
            
            #line 197 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.InitializeAsUserControl(this.Page);
            
            #line default
            #line hidden
            
            #line 197 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "menu";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextFirst() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 202 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textFirst = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 202 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textFirst";
            
            #line default
            #line hidden
            
            #line 202 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 202 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidator1() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "RequiredFieldValidator1";
            
            #line default
            #line hidden
            
            #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ControlToValidate = "textFirst";
            
            #line default
            #line hidden
            
            #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ErrorMessage = "First Name is required.";
            
            #line default
            #line hidden
            
            #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 203 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextLast() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 211 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textLast = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 211 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textLast";
            
            #line default
            #line hidden
            
            #line 211 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 211 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidatorLast() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidatorLast = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "RequiredFieldValidatorLast";
            
            #line default
            #line hidden
            
            #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ControlToValidate = "textLast";
            
            #line default
            #line hidden
            
            #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ErrorMessage = "Last Name is required.";
            
            #line default
            #line hidden
            
            #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 212 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextEmail() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 220 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textEmail = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 220 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textEmail";
            
            #line default
            #line hidden
            
            #line 220 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 220 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 255;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator1() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.RegularExpressionValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "RegularExpressionValidator1";
            
            #line default
            #line hidden
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ControlToValidate = "textEmail";
            
            #line default
            #line hidden
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "validator";
            
            #line default
            #line hidden
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ErrorMessage = "Invalid EMail, please enter again.";
            
            #line default
            #line hidden
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 221 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ValidationExpression = "\\w+([-+.\']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 230 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 230 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textPassword";
            
            #line default
            #line hidden
            
            #line 230 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 20;
            
            #line default
            #line hidden
            
            #line 230 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 230 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidatorPwd() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidatorPwd = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "RequiredFieldValidatorPwd";
            
            #line default
            #line hidden
            
            #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ControlToValidate = "textPassword";
            
            #line default
            #line hidden
            
            #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ErrorMessage = "Password is required.";
            
            #line default
            #line hidden
            
            #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 231 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::eWorld.UI.MaskedTextBox @__BuildControltextPhone() {
            global::eWorld.UI.MaskedTextBox @__ctrl;
            
            #line 239 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::eWorld.UI.MaskedTextBox();
            
            #line default
            #line hidden
            this.textPhone = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 239 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textPhone";
            
            #line default
            #line hidden
            
            #line 239 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 239 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Mask = "(999) 999-9999";
            
            #line default
            #line hidden
            
            #line 239 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 20;
            
            #line default
            #line hidden
            
            #line 239 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ValidationExpression = "((\\(\\d{3}\\) ?)|(\\d{3}-))?\\d{3}-\\d{4}";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextFBLog() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 247 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textFBLog = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 247 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textFBLog";
            
            #line default
            #line hidden
            
            #line 247 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 247 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextFBPass() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 254 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textFBPass = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 254 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textFBPass";
            
            #line default
            #line hidden
            
            #line 254 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 254 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 254 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextLinLog() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 261 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textLinLog = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 261 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textLinLog";
            
            #line default
            #line hidden
            
            #line 261 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 261 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextLinPass() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 268 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textLinPass = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 268 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textLinPass";
            
            #line default
            #line hidden
            
            #line 268 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 268 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 268 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextTwitLog() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 275 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textTwitLog = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 275 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textTwitLog";
            
            #line default
            #line hidden
            
            #line 275 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 275 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextTwitPass() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 282 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textTwitPass = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 282 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "textTwitPass";
            
            #line default
            #line hidden
            
            #line 282 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.MaxLength = 50;
            
            #line default
            #line hidden
            
            #line 282 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 282 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ValidationSummary @__BuildControlvalidJob() {
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl;
            
            #line 287 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ValidationSummary();
            
            #line default
            #line hidden
            this.validJob = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 287 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "validJob";
            
            #line default
            #line hidden
            
            #line 287 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ShowMessageBox = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbuttonSubmit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 288 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.buttonSubmit = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 288 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "buttonSubmit";
            
            #line default
            #line hidden
            
            #line 288 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "margin-left: 100px");
            
            #line default
            #line hidden
            
            #line 288 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Text = "Submit";
            
            #line default
            #line hidden
            
            #line 288 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.Click += new System.EventHandler(this.buttonSubmit_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t<!-- #BeginEditable \"Content\" -->\r\n\t\t\t\t"));
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl1;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl1 = this.@__BuildControlToolkitScriptManager1();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t"));
            
            #line default
            #line hidden
            global::ASP.controls_adminmenu_ascx @__ctrl2;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl2 = this.@__BuildControlmenu();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<label for=\"textFirst\">\r\n\t\t\t\t\t\t\tF" +
                        "irst Name:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl3 = this.@__BuildControltextFirst();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl4;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl4 = this.@__BuildControlRequiredFieldValidator1();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textLast\">\r\n\t\t\t\t\t\t\tLast Name:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl5;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl5 = this.@__BuildControltextLast();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl6;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl6 = this.@__BuildControlRequiredFieldValidatorLast();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textEmail\">\r\n\t\t\t\t\t\t\tEmail:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl7;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl7 = this.@__BuildControltextEmail();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl8;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl8 = this.@__BuildControlRegularExpressionValidator1();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textPassword\">\r\n\t\t\t\t\t\t\tPassword:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl9;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl9 = this.@__BuildControltextPassword();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl10;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl10 = this.@__BuildControlRequiredFieldValidatorPwd();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl10);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textPhone\">\r\n\t\t\t\t\t\t\tPhone:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::eWorld.UI.MaskedTextBox @__ctrl11;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl11 = this.@__BuildControltextPhone();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl11);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textFBLog\">\r\n\t\t\t\t\t\t\tFacebook Login:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl12;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl12 = this.@__BuildControltextFBLog();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl12);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textFBPass\">\r\n\t\t\t\t\t\t\tFacebook Password:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl13;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl13 = this.@__BuildControltextFBPass();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl13);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textLinLog\">\r\n\t\t\t\t\t\t\tLinkedIn Login:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl14;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl14 = this.@__BuildControltextLinLog();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl14);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textLinPass\">\r\n\t\t\t\t\t\t\tLinkedIn Password:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl15;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl15 = this.@__BuildControltextLinPass();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl15);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textTwitLog\">\r\n\t\t\t\t\t\t\tTwitter Login:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl16;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl16 = this.@__BuildControltextTwitLog();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl16);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textTwitPass\">\r\n\t\t\t\t\t\t\tTwitter Password:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl17;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl17 = this.@__BuildControltextTwitPass();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl17);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span style=\"width: 400px; padding-" +
                        "left: 140px\">\r\n\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl18;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl18 = this.@__BuildControlvalidJob();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl18);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl19;
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl19 = this.@__BuildControlbuttonSubmit();
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl19);
            
            #line default
            #line hidden
            
            #line 194 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t<input name=\"buttonReset\" style=\"margin-left: 15px;\" type=\"reset\" value=\"" +
                        "Reset\" />\r\n\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t\t<!-- #EndEditable -->\r\n\t\t\t\t"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::ASP.Copyright @__BuildControlcopy() {
            global::ASP.Copyright @__ctrl;
            
            #line 299 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl = new global::ASP.Copyright();
            
            #line default
            #line hidden
            this.copy = @__ctrl;
            
            #line 299 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.InitializeAsUserControl(this.Page);
            
            #line default
            #line hidden
            
            #line 299 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.ID = "copy";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(adminuser_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.EnableViewState = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.o" +
                        "rg/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<!-- #BeginTemplate \"templates/a" +
                        "greatis.dwt\" -->\r\n\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(14771, 1401, true));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"td3\">\r\n\t\t\t\t"));
            
            #line default
            #line hidden
            global::ASP.Copyright @__ctrl3;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__ctrl3 = this.@__BuildControlcopy();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminuser.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(16172, 730, true));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.adminuser_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.adminuser_aspx.@__fileDependencies);
            this.ValidateRequestMode = System.Web.UI.ValidateRequestMode.Disabled;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 58955386;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
