#pragma checksum "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0B37CEB9FE7A3271423EDE8EDE07D66210B1E9F1"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class AdminJobs : System.Web.SessionState.IRequiresSessionState {
    
    
    #line 83 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    protected global::AjaxControlToolkit.ToolkitScriptManager ToolkitScriptManager1;
    
    #line default
    #line hidden
    
    
    #line 84 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    protected global::ASP.controls_adminmenu_ascx menu;
    
    #line default
    #line hidden
    
    
    #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    protected global::System.Web.UI.WebControls.GridView grid;
    
    #line default
    #line hidden
    
    
    #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    protected global::System.Web.UI.WebControls.SqlDataSource sqlJob;
    
    #line default
    #line hidden
    
    
    #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    
    #line default
    #line hidden
    
    
    #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    protected global::ASP.Copyright copy;
    
    #line default
    #line hidden
    
    protected System.Web.Profile.DefaultProfile Profile {
        get {
            return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
        }
    }
    
    protected System.Web.HttpApplication ApplicationInstance {
        get {
            return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
        }
    }
}
namespace ASP {
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using Telerik.Web.UI;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using AjaxControlToolkit;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class adminjobs_aspx : global::AdminJobs, System.Web.IHttpHandler {
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public adminjobs_aspx() {
            string[] dependencies;
            
            #line 912304 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx.cs"
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/adminjobs.aspx";
            
            #line default
            #line hidden
            if ((global::ASP.adminjobs_aspx.@__initialized == false)) {
                global::ASP.adminjobs_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[4];
                dependencies[0] = "~/adminjobs.aspx";
                dependencies[1] = "~/adminjobs.aspx.cs";
                dependencies[2] = "~/controls/adminmenu.ascx";
                dependencies[3] = "~/controls/Copyright.ascx";
                global::ASP.adminjobs_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.adminjobs_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 18 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Content = "text/html; charset=iso-8859-1";
            
            #line default
            #line hidden
            
            #line 18 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("http-equiv", "Content-Type");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 20 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 20 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("AGREATIS&#8480;, Inc. - View All Jobs"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Href = "agreatis.css";
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 22 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 31 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Href = "Content/kendo/2012.3.1114/kendo.metro.min.css";
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 31 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 32 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Href = "Content/kendo/2012.3.1114/kendo.common.min.css";
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 32 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 50 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 50 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Content = "http://www.agreatis.com/images/logo_og.jpg";
            
            #line default
            #line hidden
            
            #line 50 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 51 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 51 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Content = "image/png";
            
            #line default
            #line hidden
            
            #line 51 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:type");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 52 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 52 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Content = "720";
            
            #line default
            #line hidden
            
            #line 52 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:width");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control11() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 53 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 53 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Content = "440";
            
            #line default
            #line hidden
            
            #line 53 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:height");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("prefix", "og: http://ogp.me/ns#");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <!-- \r\n\t****************\r\n\tDescription: AGREATIS, Inc.\r\n\tCalled By : http:/" +
                        "/www.agreatis.com\r\n\tCreated: DonBosco Paily 07/30/2013\r\n\tLast Modified: DonBosco" +
                        " Paily 07/30/2013\r\n\t****************\r\n\t-->\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <!-- #BeginEditable \"doctitle\" -->\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl2;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <!-- #EndEditable -->\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl3;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(5839, 472, true));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl4;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl4 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl5;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(6311, 406, true));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl6;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl6 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl7;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl7 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl8;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl8 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl9;
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl9 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 9 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(6717, 331, true));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::AjaxControlToolkit.ToolkitScriptManager @__BuildControlToolkitScriptManager1() {
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl;
            
            #line 83 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::AjaxControlToolkit.ToolkitScriptManager();
            
            #line default
            #line hidden
            this.ToolkitScriptManager1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 83 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "ToolkitScriptManager1";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::ASP.controls_adminmenu_ascx @__BuildControlmenu() {
            global::ASP.controls_adminmenu_ascx @__ctrl;
            
            #line 84 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::ASP.controls_adminmenu_ascx();
            
            #line default
            #line hidden
            this.menu = @__ctrl;
            
            #line 84 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.InitializeAsUserControl(this.Page);
            
            #line default
            #line hidden
            
            #line 84 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "menu";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLinkField @__BuildControl__control13() {
            global::System.Web.UI.WebControls.HyperLinkField @__ctrl;
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLinkField();
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataNavigateUrlFields = new string[] {
                    "Id"};
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataNavigateUrlFormatString = "adminjob.aspx?id={0}";
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataTextField = "JobCode";
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "JobCode";
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 91 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.Wrap = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control14() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "ClientJobReqCode";
            
            #line default
            #line hidden
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Client Code";
            
            #line default
            #line hidden
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 93 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.Wrap = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control15() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 94 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 94 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "JobTitle";
            
            #line default
            #line hidden
            
            #line 94 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Title";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control16() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "Location";
            
            #line default
            #line hidden
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Location";
            
            #line default
            #line hidden
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(170D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 95 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.Wrap = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control17() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 96 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 96 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "State";
            
            #line default
            #line hidden
            
            #line 96 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "State";
            
            #line default
            #line hidden
            
            #line 96 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(60D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control18() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 97 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 97 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "JobType";
            
            #line default
            #line hidden
            
            #line 97 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Type";
            
            #line default
            #line hidden
            
            #line 97 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(80D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control19() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "PostedOn";
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataFormatString = "{0:d}";
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Posted On";
            
            #line default
            #line hidden
            
            #line 99 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control20() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 100 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 100 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "Expiry";
            
            #line default
            #line hidden
            
            #line 100 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataFormatString = "{0:d}";
            
            #line default
            #line hidden
            
            #line 100 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Expiry";
            
            #line default
            #line hidden
            
            #line 100 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.CssClass = "hidden";
            
            #line default
            #line hidden
            
            #line 100 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.CssClass = "hidden";
            
            #line default
            #line hidden
            
            #line 100 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control21() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 101 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 101 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "OFCCPRequired";
            
            #line default
            #line hidden
            
            #line 101 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "OFCCP?";
            
            #line default
            #line hidden
            
            #line 101 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(60D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.BoundField @__BuildControl__control22() {
            global::System.Web.UI.WebControls.BoundField @__ctrl;
            
            #line 102 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.BoundField();
            
            #line default
            #line hidden
            
            #line 102 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataField = "Status";
            
            #line default
            #line hidden
            
            #line 102 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Status";
            
            #line default
            #line hidden
            
            #line 102 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.CssClass = "hidden";
            
            #line default
            #line hidden
            
            #line 102 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.CssClass = "hidden";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control25() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "linkSubmission";
            
            #line default
            #line hidden
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ImageUrl = "~/images/resume.png";
            
            #line default
            #line hidden
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ToolTip = "Submissions";
            
            #line default
            #line hidden
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.CssClass = "linkImage";
            
            #line default
            #line hidden
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control25);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control25(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.HyperLink dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.HyperLink)(sender));
            
            #line default
            #line hidden
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 107 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget.NavigateUrl = global::System.Convert.ToString( Eval("Id", "adminshowsubmissions.aspx?id={0}") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.HyperLink @__BuildControl__control26() {
            global::System.Web.UI.WebControls.HyperLink @__ctrl;
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.HyperLink();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "HyperLink1";
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ToolTip = "Submissions";
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control26);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control26(object sender, System.EventArgs e) {
            System.Web.UI.WebControls.HyperLink dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget = ((System.Web.UI.WebControls.HyperLink)(sender));
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget.NavigateUrl = global::System.Convert.ToString( Eval("Id", "adminshowsubmissions.aspx?id={0}") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 108 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget.Text = global::System.Convert.ToString(Eval("CountResumes", "Count: ({0})") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control24(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl1;
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control25();
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.HyperLink @__ctrl2;
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl2 = this.@__BuildControl__control26();
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                \r\n                            "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control23() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control24), null);
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.VerticalAlign = global::System.Web.UI.WebControls.VerticalAlign.Bottom;
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Submissions";
            
            #line default
            #line hidden
            
            #line 105 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(120D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ImageButton @__BuildControl__control29() {
            global::System.Web.UI.WebControls.ImageButton @__ctrl;
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ImageButton();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "LinkButton1";
            
            #line default
            #line hidden
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.CausesValidation = false;
            
            #line default
            #line hidden
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.CommandName = "Delete";
            
            #line default
            #line hidden
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ImageUrl = "~/images/active.png";
            
            #line default
            #line hidden
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(16D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Height = new System.Web.UI.WebControls.Unit(16D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 120 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.OnClientClick = " return confirm(\'Are you certain you want to toggle the Status for this Job?\'); ";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Telerik.Web.UI.RadSocialButton @__BuildControl__control32() {
            global::Telerik.Web.UI.RadSocialButton @__ctrl;
            
            #line 127 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::Telerik.Web.UI.RadSocialButton();
            
            #line default
            #line hidden
            
            #line 127 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.SocialNetType = global::Telerik.Web.UI.SocialNetType.LinkedIn;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Telerik.Web.UI.RadSocialButton @__BuildControl__control33() {
            global::Telerik.Web.UI.RadSocialButton @__ctrl;
            
            #line 128 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::Telerik.Web.UI.RadSocialButton();
            
            #line default
            #line hidden
            
            #line 128 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.SocialNetType = global::Telerik.Web.UI.SocialNetType.ShareOnFacebook;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Telerik.Web.UI.RadSocialButton @__BuildControl__control34() {
            global::Telerik.Web.UI.RadSocialButton @__ctrl;
            
            #line 129 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::Telerik.Web.UI.RadSocialButton();
            
            #line default
            #line hidden
            
            #line 129 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.SocialNetType = global::Telerik.Web.UI.SocialNetType.ShareOnTwitter;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Telerik.Web.UI.RadSocialButton @__BuildControl__control35() {
            global::Telerik.Web.UI.RadSocialButton @__ctrl;
            
            #line 130 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::Telerik.Web.UI.RadSocialButton();
            
            #line default
            #line hidden
            
            #line 130 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.SocialNetType = global::Telerik.Web.UI.SocialNetType.ShareOnPinterest;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Telerik.Web.UI.RadGoogleButton @__BuildControl__control36() {
            global::Telerik.Web.UI.RadGoogleButton @__ctrl;
            
            #line 131 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::Telerik.Web.UI.RadGoogleButton();
            
            #line default
            #line hidden
            
            #line 131 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.AnnotationType = global::Telerik.Web.UI.GooglePlusOneAnnotation.None;
            
            #line default
            #line hidden
            
            #line 131 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ButtonSize = global::Telerik.Web.UI.GooglePlusOneSize.Small;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control31(Telerik.Web.UI.SocialShare.GenericSocialButtonsCollection<Telerik.Web.UI.RadSocialButtonBase> @__ctrl) {
            global::Telerik.Web.UI.RadSocialButton @__ctrl1;
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control32();
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::Telerik.Web.UI.RadSocialButton @__ctrl2;
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl2 = this.@__BuildControl__control33();
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::Telerik.Web.UI.RadSocialButton @__ctrl3;
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl3 = this.@__BuildControl__control34();
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::Telerik.Web.UI.RadSocialButton @__ctrl4;
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl4 = this.@__BuildControl__control35();
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::Telerik.Web.UI.RadGoogleButton @__ctrl5;
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl5 = this.@__BuildControl__control36();
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Telerik.Web.UI.RadSocialShare @__BuildControl__control30() {
            global::Telerik.Web.UI.RadSocialShare @__ctrl;
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::Telerik.Web.UI.RadSocialShare();
            
            #line default
            #line hidden
            @__ctrl.TemplateControl = this;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.BorderStyle = global::System.Web.UI.WebControls.BorderStyle.None;
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            this.@__BuildControl__control31(@__ctrl.MainButtons);
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataBinding += new System.EventHandler(this.@__DataBinding__control30);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        public void @__DataBinding__control30(object sender, System.EventArgs e) {
            Telerik.Web.UI.RadSocialShare dataBindingExpressionBuilderTarget;
            System.Web.UI.IDataItemContainer Container;
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget = ((Telerik.Web.UI.RadSocialShare)(sender));
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            Container = ((System.Web.UI.IDataItemContainer)(dataBindingExpressionBuilderTarget.BindingContainer));
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget.UrlToShare = global::System.Convert.ToString(Eval("Link")  + "||" + Eval("ShortText"), global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
            
            #line 125 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            dataBindingExpressionBuilderTarget.TitleToShare = global::System.Convert.ToString(Eval("JobTitle") , global::System.Globalization.CultureInfo.CurrentCulture);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control28(System.Web.UI.Control @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                "));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ImageButton @__ctrl1;
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control29();
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                                \r\n                                \r\n           " +
                        "                     "));
            
            #line default
            #line hidden
            global::Telerik.Web.UI.RadSocialShare @__ctrl2;
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl2 = this.@__BuildControl__control30();
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n                            "));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TemplateField @__BuildControl__control27() {
            global::System.Web.UI.WebControls.TemplateField @__ctrl;
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TemplateField();
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemTemplate = new System.Web.UI.CompiledBindableTemplateBuilder(new System.Web.UI.BuildTemplateMethod(this.@__BuildControl__control28), null);
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.HorizontalAlign = global::System.Web.UI.WebControls.HorizontalAlign.Center;
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ItemStyle.VerticalAlign = global::System.Web.UI.WebControls.VerticalAlign.Bottom;
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderStyle.Width = new System.Web.UI.WebControls.Unit(155D, global::System.Web.UI.WebControls.UnitType.Pixel);
            
            #line default
            #line hidden
            
            #line 118 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.HeaderText = "Post To";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control12(System.Web.UI.WebControls.DataControlFieldCollection @__ctrl) {
            global::System.Web.UI.WebControls.HyperLinkField @__ctrl1;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control13();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl2;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl2 = this.@__BuildControl__control14();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl3;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl3 = this.@__BuildControl__control15();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl4;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl4 = this.@__BuildControl__control16();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl5;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl5 = this.@__BuildControl__control17();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl5);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl6;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl6 = this.@__BuildControl__control18();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl6);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl7;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl7 = this.@__BuildControl__control19();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl7);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl8;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl8 = this.@__BuildControl__control20();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl9;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl9 = this.@__BuildControl__control21();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl9);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.BoundField @__ctrl10;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl10 = this.@__BuildControl__control22();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl10);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl11;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl11 = this.@__BuildControl__control23();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl11);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TemplateField @__ctrl12;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl12 = this.@__BuildControl__control27();
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl12);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.GridView @__BuildControlgrid() {
            global::System.Web.UI.WebControls.GridView @__ctrl;
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.GridView();
            
            #line default
            #line hidden
            this.grid = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "grid";
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.AutoGenerateColumns = false;
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataKeyNames = new string[] {
                    "Id"};
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DataSourceID = "sqlJob";
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.EmptyDataText = "No Jobs";
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ShowHeaderWhenEmpty = true;
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(100D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            this.@__BuildControl__control12(@__ctrl.Columns);
            
            #line default
            #line hidden
            
            #line 88 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.RowDataBound += new System.Web.UI.WebControls.GridViewRowEventHandler(this.gridJob_RowDataBound);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Parameter @__BuildControl__control38() {
            global::System.Web.UI.WebControls.Parameter @__ctrl;
            
            #line 142 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Parameter();
            
            #line default
            #line hidden
            
            #line 142 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Name = "Id";
            
            #line default
            #line hidden
            
            #line 142 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Type = global::System.TypeCode.Int32;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control37(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.Parameter @__ctrl1;
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control38();
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.QueryStringParameter @__BuildControl__control40() {
            global::System.Web.UI.WebControls.QueryStringParameter @__ctrl;
            
            #line 145 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.QueryStringParameter();
            
            #line default
            #line hidden
            
            #line 145 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Name = "Status";
            
            #line default
            #line hidden
            
            #line 145 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Type = global::System.TypeCode.Boolean;
            
            #line default
            #line hidden
            
            #line 145 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DefaultValue = "true";
            
            #line default
            #line hidden
            
            #line 145 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.QueryStringField = "s";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControl__control39(System.Web.UI.WebControls.ParameterCollection @__ctrl) {
            global::System.Web.UI.WebControls.QueryStringParameter @__ctrl1;
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control40();
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.Add(@__ctrl1);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.SqlDataSource @__BuildControlsqlJob() {
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl;
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.SqlDataSource();
            
            #line default
            #line hidden
            this.sqlJob = @__ctrl;
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "sqlJob";
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DeleteCommand = "DeleteJob";
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.DeleteCommandType = global::System.Web.UI.WebControls.SqlDataSourceCommandType.StoredProcedure;
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ProviderName = "System.Data.SqlClient";
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.SelectCommand = "GetAllJobs";
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.SelectCommandType = global::System.Web.UI.WebControls.SqlDataSourceCommandType.StoredProcedure;
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            this.@__BuildControl__control37(@__ctrl.DeleteParameters);
            
            #line default
            #line hidden
            
            #line 138 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            this.@__BuildControl__control39(@__ctrl.SelectParameters);
            
            #line default
            #line hidden
            @__ctrl.ConnectionString = global::System.Convert.ToString(System.Web.Compilation.AppSettingsExpressionBuilder.GetAppSetting("ConnStr", typeof(System.Web.UI.WebControls.SqlDataSource), "ConnectionString"), global::System.Globalization.CultureInfo.CurrentCulture);
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            global::AjaxControlToolkit.ToolkitScriptManager @__ctrl1;
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControlToolkitScriptManager1();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::ASP.controls_adminmenu_ascx @__ctrl2;
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl2 = this.@__BuildControlmenu();
            
            #line default
            #line hidden
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.GridView @__ctrl3;
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl3 = this.@__BuildControlgrid();
            
            #line default
            #line hidden
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.SqlDataSource @__ctrl4;
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl4 = this.@__BuildControlsqlJob();
            
            #line default
            #line hidden
            
            #line 80 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            @__ctrl.SetRenderMethodDelegate(new System.Web.UI.RenderMethod(this.@__Renderform1));
            return @__ctrl;
        }
        
        private void @__Renderform1(System.Web.UI.HtmlTextWriter @__w, System.Web.UI.Control parameterContainer) {
            @__w.Write("\r\n        <div style=\"width: 96%; margin: 10px; padding: 5px; margin-bottom: 40px" +
                    ";\">\r\n            <!-- #BeginEditable \"Content\" -->\r\n            ");
            parameterContainer.Controls[0].RenderControl(@__w);
            @__w.Write("\r\n            ");
            parameterContainer.Controls[1].RenderControl(@__w);
            this.WriteUTF8ResourceString(@__w, 7048, 268, true);
            
            #line 87 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
                                                                                           @__w.Write(string.IsNullOrWhiteSpace(Request.QueryString["s"]) || Request.QueryString["s"] == "true" ? "false" : "true" );

            
            #line default
            #line hidden
            @__w.Write("\'; \" style=\"margin: 20px\">");
            
            #line 87 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
                                                                                                                                                                                                                                       @__w.Write(string.IsNullOrWhiteSpace(Request.QueryString["s"]) || Request.QueryString["s"] == "true" ? "Show Inactive Jobs" : "Show Active Jobs" );

            
            #line default
            #line hidden
            @__w.Write("</button>\r\n                ");
            parameterContainer.Controls[2].RenderControl(@__w);
            @__w.Write("\r\n                ");
            parameterContainer.Controls[3].RenderControl(@__w);
            @__w.Write("\r\n            </div>\r\n            <!-- #EndEditable -->\r\n        </div>\r\n    ");
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::ASP.Copyright @__BuildControlcopy() {
            global::ASP.Copyright @__ctrl;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl = new global::ASP.Copyright();
            
            #line default
            #line hidden
            this.copy = @__ctrl;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.InitializeAsUserControl(this.Page);
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.ID = "copy";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(adminjobs_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.EnableViewState = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.o" +
                        "rg/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/" +
                        "xhtml\">\r\n\r\n<!-- #BeginTemplate \"templates/agreatis_admin.dwt\" -->\r\n\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<body>\r\n    <div style=\"text-align: center\">\r\n        <a href=\"index.aspx\">\r\n  " +
                        "          <img alt=\"Header\" src=\"images/Hdrs_imgAdmin.jpg\" style=\"border: none\" " +
                        "/></a>\r\n    </div>\r\n    <!-- #BeginEditable \"jqueryImg\" -->\r\n    <!-- #EndEditab" +
                        "le -->\r\n    "));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n    <div class=\"td3 copyAdmin\">\r\n        "));
            
            #line default
            #line hidden
            global::ASP.Copyright @__ctrl3;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__ctrl3 = this.@__BuildControlcopy();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(7316, 6844, true));
            
            #line default
            #line hidden
        }
        
        
        #line 912304 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminjobs.aspx.cs"
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.adminjobs_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.adminjobs_aspx.@__fileDependencies);
            this.ValidateRequestMode = System.Web.UI.ValidateRequestMode.Disabled;
        }
        
        #line default
        #line hidden
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return -1457071146;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
