#pragma checksum "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "E821392B7D83DB82BFB9F23FF241B2850DB2F939"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    
    #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Web.UI.WebControls.Expressions;
    
    #line default
    #line hidden
    
    #line 325 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections;
    
    #line default
    #line hidden
    
    #line 331 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text;
    
    #line default
    #line hidden
    
    #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Web.UI;
    
    #line default
    #line hidden
    
    #line 326 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 5 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Globalization;
    
    #line default
    #line hidden
    
    #line 330 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Linq;
    
    #line default
    #line hidden
    
    #line 343 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Xml.Linq;
    
    #line default
    #line hidden
    
    #line 190 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using ASP;
    
    #line default
    #line hidden
    
    #line 336 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.SessionState;
    
    #line default
    #line hidden
    
    #line 327 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 333 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web;
    
    #line default
    #line hidden
    
    #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Web.DynamicData;
    
    #line default
    #line hidden
    
    #line 334 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Caching;
    
    #line default
    #line hidden
    
    #line 338 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Profile;
    
    #line default
    #line hidden
    
    #line 328 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.ComponentModel.DataAnnotations;
    
    #line default
    #line hidden
    
    #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Web.UI.WebControls;
    
    #line default
    #line hidden
    
    #line 3 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Data;
    
    #line default
    #line hidden
    
    #line 337 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.Security;
    
    #line default
    #line hidden
    
    #line 324 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System;
    
    #line default
    #line hidden
    
    #line 4 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Data.SqlClient;
    
    #line default
    #line hidden
    
    #line 332 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Text.RegularExpressions;
    
    #line default
    #line hidden
    
    #line 329 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Configuration;
    
    #line default
    #line hidden
    
    #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
    using System.Web.UI.WebControls.WebParts;
    
    #line default
    #line hidden
    
    #line 342 "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\web.config"
    using System.Web.UI.HtmlControls;
    
    #line default
    #line hidden
    
    
    [System.Runtime.CompilerServices.CompilerGlobalScopeAttribute()]
    public class adminlogin_aspx : global::System.Web.UI.Page, System.Web.SessionState.IRequiresSessionState, System.Web.IHttpHandler {
        
        
        #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::System.Web.UI.WebControls.TextBox textEmail;
        
        #line default
        #line hidden
        
        
        #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::System.Web.UI.WebControls.RegularExpressionValidator RegularExpressionValidator1;
        
        #line default
        #line hidden
        
        
        #line 171 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::System.Web.UI.WebControls.TextBox textPassword;
        
        #line default
        #line hidden
        
        
        #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidatorPwd;
        
        #line default
        #line hidden
        
        
        #line 179 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::System.Web.UI.WebControls.ValidationSummary validJob;
        
        #line default
        #line hidden
        
        
        #line 180 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::System.Web.UI.WebControls.Button buttonSubmit;
        
        #line default
        #line hidden
        
        
        #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        #line default
        #line hidden
        
        
        #line 190 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
        protected global::ASP.Copyright copy;
        
        #line default
        #line hidden
        
        private static bool @__initialized;
        
        private static object @__stringResource;
        
        private static object @__fileDependencies;
        
        
        #line 7 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
                       

	void Page_Init(object sender, EventArgs e)
	{
		if (Request.Cookies["UserName"] != null && Request.Cookies["UserName"].ToString() != "")
		{
			Response.Redirect("~/adminusers.aspx", true);
		}
	}

	void buttonSubmit_Click(object sender, EventArgs e)
	{
		using (SqlConnection _con = new SqlConnection(ConfigurationManager.AppSettings["ConnStr"]))
		{
			using (SqlCommand _command = new SqlCommand("CheckUser", _con)
			{
				CommandType = CommandType.StoredProcedure
			})
			{
				_command.Parameters.AddWithValue("@Email", textEmail.Text);
				_command.Parameters.AddWithValue("@Password", textPassword.Text);
				_con.Open();
				using (SqlDataReader _read = _command.ExecuteReader())
				{
					if (_read.HasRows)
					{
						while (_read.Read())
						{
							Response.Cookies["UserId"].Value = _read.GetInt32(0).ToString(CultureInfo.InvariantCulture);
							Response.Cookies["UserName"].Value = textEmail.Text;
							Response.Cookies["Admin"].Value = (_read.GetInt32(0) == 1).ToString(CultureInfo.InvariantCulture);
						}
					}
					else
					{
						ClientScript.RegisterClientScriptBlock(typeof(string), Guid.NewGuid().ToString(), "alert('Invalid User Name/Password')", true);
						return;
					}
				}
				Response.Redirect("adminjobs.aspx", true);
			}
		}
	}

        #line default
        #line hidden
        
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public adminlogin_aspx() {
            string[] dependencies;
            ((global::System.Web.UI.Page)(this)).AppRelativeVirtualPath = "~/adminlogin.aspx";
            if ((global::ASP.adminlogin_aspx.@__initialized == false)) {
                global::ASP.adminlogin_aspx.@__stringResource = this.ReadStringResource();
                dependencies = new string[2];
                dependencies[0] = "~/adminlogin.aspx";
                dependencies[1] = "~/controls/Copyright.ascx";
                global::ASP.adminlogin_aspx.@__fileDependencies = this.GetWrappedFileDependencies(dependencies);
                global::ASP.adminlogin_aspx.@__initialized = true;
            }
            this.Server.ScriptTimeout = 30000000;
        }
        
        protected System.Web.Profile.DefaultProfile Profile {
            get {
                return ((System.Web.Profile.DefaultProfile)(this.Context.Profile));
            }
        }
        
        protected System.Web.HttpApplication ApplicationInstance {
            get {
                return ((System.Web.HttpApplication)(this.Context.ApplicationInstance));
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control3() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 64 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 64 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Content = "text/html; charset=iso-8859-1";
            
            #line default
            #line hidden
            
            #line 64 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("http-equiv", "Content-Type");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control4() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 65 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 65 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Content = "http://www.agreatis.com/images/logo_og.jpg";
            
            #line default
            #line hidden
            
            #line 65 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control5() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 66 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 66 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Content = "image/png";
            
            #line default
            #line hidden
            
            #line 66 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:type");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control6() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 67 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 67 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Content = "720";
            
            #line default
            #line hidden
            
            #line 67 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:width");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlMeta @__BuildControl__control7() {
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl;
            
            #line 68 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlMeta();
            
            #line default
            #line hidden
            
            #line 68 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Content = "440";
            
            #line default
            #line hidden
            
            #line 68 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("property", "og:image:height");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlTitle @__BuildControl__control8() {
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl;
            
            #line 70 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlTitle();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 70 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("Logon - Agreatis&trade;, Inc."));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control9() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 72 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 72 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Href = "agreatis.css";
            
            #line default
            #line hidden
            
            #line 72 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 72 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control10() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 81 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 81 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Href = "Content/kendo/2012.3.1114/kendo.metro.min.css";
            
            #line default
            #line hidden
            
            #line 81 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 81 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlLink @__BuildControl__control11() {
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl;
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlLink();
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Href = "Content/kendo/2012.3.1114/kendo.common.min.css";
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("rel", "stylesheet");
            
            #line default
            #line hidden
            
            #line 82 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("type", "text/css");
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlHead @__BuildControl__control2() {
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlHead("head");
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("prefix", "og: http://ogp.me/ns#");
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t<!-- \r\n\t****************\r\n\tDescription: AGREATIS, Inc.\r\n\tCalled By : http://ww" +
                        "w.agreatis.com\r\n\tCreated: DonBosco Paily 07/30/2013\r\n\tLast Modified: DonBosco Pa" +
                        "ily 07/30/2013\r\n\t****************\r\n\t-->\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl1;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl1 = this.@__BuildControl__control3();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl2;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl2 = this.@__BuildControl__control4();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl3;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl3 = this.@__BuildControl__control5();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl4;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl4 = this.@__BuildControl__control6();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlMeta @__ctrl5;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl5 = this.@__BuildControl__control7();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t<!-- #BeginEditable \"doctitle\" -->\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlTitle @__ctrl6;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl6 = this.@__BuildControl__control8();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t<!-- #EndEditable -->\r\n\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl7;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl7 = this.@__BuildControl__control9();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl7);
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(13583, 439, true));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl8;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl8 = this.@__BuildControl__control10();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl8);
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlLink @__ctrl9;
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl9 = this.@__BuildControl__control11();
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl9);
            
            #line default
            #line hidden
            
            #line 55 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(14022, 691, true));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextEmail() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textEmail = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "textEmail";
            
            #line default
            #line hidden
            
            #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 161 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.MaxLength = 255;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RegularExpressionValidator @__BuildControlRegularExpressionValidator1() {
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl;
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RegularExpressionValidator();
            
            #line default
            #line hidden
            this.RegularExpressionValidator1 = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "RegularExpressionValidator1";
            
            #line default
            #line hidden
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ControlToValidate = "textEmail";
            
            #line default
            #line hidden
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.CssClass = "validator";
            
            #line default
            #line hidden
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ErrorMessage = "Invalid EMail, please enter again.";
            
            #line default
            #line hidden
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 162 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ValidationExpression = "\\w+([-+.\']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.TextBox @__BuildControltextPassword() {
            global::System.Web.UI.WebControls.TextBox @__ctrl;
            
            #line 171 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.TextBox();
            
            #line default
            #line hidden
            this.textPassword = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 171 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "textPassword";
            
            #line default
            #line hidden
            
            #line 171 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.MaxLength = 20;
            
            #line default
            #line hidden
            
            #line 171 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.CssClass = "text";
            
            #line default
            #line hidden
            
            #line 171 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.TextMode = global::System.Web.UI.WebControls.TextBoxMode.Password;
            
            #line default
            #line hidden
            
            #line 171 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Width = new System.Web.UI.WebControls.Unit(30D, global::System.Web.UI.WebControls.UnitType.Percentage);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.RequiredFieldValidator @__BuildControlRequiredFieldValidatorPwd() {
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl;
            
            #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.RequiredFieldValidator();
            
            #line default
            #line hidden
            this.RequiredFieldValidatorPwd = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "RequiredFieldValidatorPwd";
            
            #line default
            #line hidden
            
            #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ControlToValidate = "textPassword";
            
            #line default
            #line hidden
            
            #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Display = global::System.Web.UI.WebControls.ValidatorDisplay.Dynamic;
            
            #line default
            #line hidden
            
            #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ErrorMessage = "Password is required.";
            
            #line default
            #line hidden
            
            #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ForeColor = global::System.Drawing.Color.Red;
            
            #line default
            #line hidden
            
            #line 173 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.SetFocusOnError = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.ValidationSummary @__BuildControlvalidJob() {
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl;
            
            #line 179 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.ValidationSummary();
            
            #line default
            #line hidden
            this.validJob = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 179 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "validJob";
            
            #line default
            #line hidden
            
            #line 179 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ShowMessageBox = true;
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.WebControls.Button @__BuildControlbuttonSubmit() {
            global::System.Web.UI.WebControls.Button @__ctrl;
            
            #line 180 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.WebControls.Button();
            
            #line default
            #line hidden
            this.buttonSubmit = @__ctrl;
            @__ctrl.ApplyStyleSheetSkin(this);
            
            #line 180 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "buttonSubmit";
            
            #line default
            #line hidden
            
            #line 180 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            ((System.Web.UI.IAttributeAccessor)(@__ctrl)).SetAttribute("Style", "margin-left: 100px");
            
            #line default
            #line hidden
            
            #line 180 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Text = "Submit";
            
            #line default
            #line hidden
            
            #line 180 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.Click += new System.EventHandler(this.buttonSubmit_Click);
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Web.UI.HtmlControls.HtmlForm @__BuildControlform1() {
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::System.Web.UI.HtmlControls.HtmlForm();
            
            #line default
            #line hidden
            this.form1 = @__ctrl;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "form1";
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t<!-- #BeginEditable \"Content\" -->\r\n\t\t\t\t<h2>\r\n\t\t\t\t\tLogon to Agreatis&#8480;" +
                        ", Inc.</h2>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<label for=\"textEmail" +
                        "\">\r\n\t\t\t\t\t\t\tEmail:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl1;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl1 = this.@__BuildControltextEmail();
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RegularExpressionValidator @__ctrl2;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl2 = this.@__BuildControlRegularExpressionValidator1();
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span class=\"spanLbl\">\r\n\t\t\t\t\t\t<labe" +
                        "l for=\"textPassword\">\r\n\t\t\t\t\t\t\tPassword:</label></span> <span>\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.TextBox @__ctrl3;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl3 = this.@__BuildControltextPassword();
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.RequiredFieldValidator @__ctrl4;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl4 = this.@__BuildControlRequiredFieldValidatorPwd();
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl4);
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div>\r\n\t\t\t\t\t<span style=\"width: 400px; padding-" +
                        "left: 140px\">\r\n\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.ValidationSummary @__ctrl5;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl5 = this.@__BuildControlvalidJob();
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl5);
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t\t"));
            
            #line default
            #line hidden
            global::System.Web.UI.WebControls.Button @__ctrl6;
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl6 = this.@__BuildControlbuttonSubmit();
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl6);
            
            #line default
            #line hidden
            
            #line 153 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t\t\t</span>\r\n\t\t\t\t</div>\r\n\t\t\t\t\t<!-- #EndEditable -->\r\n\t\t\t\t"));
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::ASP.Copyright @__BuildControlcopy() {
            global::ASP.Copyright @__ctrl;
            
            #line 190 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl = new global::ASP.Copyright();
            
            #line default
            #line hidden
            this.copy = @__ctrl;
            
            #line 190 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.InitializeAsUserControl(this.Page);
            
            #line default
            #line hidden
            
            #line 190 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.ID = "copy";
            
            #line default
            #line hidden
            return @__ctrl;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void @__BuildControlTree(adminlogin_aspx @__ctrl) {
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.EnableViewState = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl.EnableViewStateMac = false;
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            this.InitializeCulture();
            
            #line default
            #line hidden
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.o" +
                        "rg/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"));
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n\r\n<!-- #BeginTemplate \"templates/a" +
                        "greatis.dwt\" -->\r\n\r\n"));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlHead @__ctrl1;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl1 = this.@__BuildControl__control2();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl1);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(14713, 1395, true));
            
            #line default
            #line hidden
            global::System.Web.UI.HtmlControls.HtmlForm @__ctrl2;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl2 = this.@__BuildControlform1();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl2);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\t\t\t</td>\r\n\t\t</tr>\r\n\t\t<tr>\r\n\t\t\t<td class=\"td3\">\r\n\t\t\t\t"));
            
            #line default
            #line hidden
            global::ASP.Copyright @__ctrl3;
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__ctrl3 = this.@__BuildControlcopy();
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(@__ctrl3);
            
            #line default
            #line hidden
            
            #line 1 "C:\Inetpub\vhosts\agreatis.com\httpdocs\adminlogin.aspx"
            @__parser.AddParsedSubObject(this.CreateResourceBasedLiteralControl(16108, 730, true));
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FrameworkInitialize() {
            base.FrameworkInitialize();
            this.SetStringResourcePointer(global::ASP.adminlogin_aspx.@__stringResource, 0);
            this.@__BuildControlTree(this);
            this.AddWrappedFileDependencies(global::ASP.adminlogin_aspx.@__fileDependencies);
            this.ValidateRequestMode = System.Web.UI.ValidateRequestMode.Disabled;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override int GetTypeHashCode() {
            return 1364971948;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override void ProcessRequest(System.Web.HttpContext context) {
            base.ProcessRequest(context);
        }
    }
}
