//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.42000")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.5")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_b0kbq3ku {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_b0kbq3ku() {
        }
        
        static object Create_ASP_services_aspx() {
            return new ASP.services_aspx();
        }
        
        static object Create_ASP_adminusers_aspx() {
            return new ASP.adminusers_aspx();
        }
        
        static object Create_ASP_adminuser_aspx() {
            return new ASP.adminuser_aspx();
        }
        
        static object Create_ASP_adminjob1_aspx() {
            return new ASP.adminjob1_aspx();
        }
        
        static object Create_ASP_register_aspx() {
            return new ASP.register_aspx();
        }
    }
}
